server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
