-- MySQL Script generated by MySQL Workbench
-- Wed Jan  7 14:57:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `railway` ;

-- -----------------------------------------------------
-- Table `railway`.`event_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`event_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`event_categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `student_code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `full_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `class_name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `faculty` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email` ON `railway`.`users` (`email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`point_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`point_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`point_types` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `code` ON `railway`.`point_types` (`code` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`semesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`semesters` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`semesters` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `status` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`events` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `semester_id` BIGINT NOT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `title` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `location` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `banner_url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `registration_deadline` DATETIME NULL DEFAULT NULL,
  `max_participants` INT NULL DEFAULT NULL,
  `point_type_id` BIGINT NOT NULL,
  `point_value` INT NOT NULL DEFAULT '0',
  `created_by` BIGINT NULL DEFAULT NULL,
  `status` ENUM('DRAFT', 'OPEN', 'CLOSED', 'DONE', 'CANCELLED') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'DRAFT',
  `event_mode` VARCHAR(20) NOT NULL DEFAULT 'ATTENDANCE',
  `survey_url` VARCHAR(500) NULL DEFAULT NULL,
  `survey_secret_code` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_events_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `railway`.`event_categories` (`id`),
  CONSTRAINT `fk_events_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `railway`.`users` (`id`),
  CONSTRAINT `fk_events_point_type`
    FOREIGN KEY (`point_type_id`)
    REFERENCES `railway`.`point_types` (`id`),
  CONSTRAINT `fk_events_semester`
    FOREIGN KEY (`semester_id`)
    REFERENCES `railway`.`semesters` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_events_semester` ON `railway`.`events` (`semester_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_events_category` ON `railway`.`events` (`category_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_events_point_type` ON `railway`.`events` (`point_type_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_events_created_by` ON `railway`.`events` (`created_by` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`event_registrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`event_registrations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`event_registrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `registration_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('REGISTERED', 'APPROVED', 'CHECKED_IN', 'COMPLETED', 'ABSENT', 'CANCELLED') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'REGISTERED',
  `checkin_time` DATETIME NULL DEFAULT NULL,
  `checkout_time` DATETIME NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reg_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `railway`.`events` (`id`),
  CONSTRAINT `fk_reg_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `railway`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uq_event_student` ON `railway`.`event_registrations` (`event_id` ASC, `student_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_reg_student` ON `railway`.`event_registrations` (`student_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`notifications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`notifications` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `title` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `content` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `type` ENUM('SYSTEM', 'EVENT', 'REMINDER') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'SYSTEM',
  `is_read` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notif_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `railway`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `fk_notif_user` ON `railway`.`notifications` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`password_reset_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`password_reset_codes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`password_reset_codes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code_hash` VARCHAR(64) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  `used_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`point_transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`point_transactions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`point_transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `student_id` BIGINT NOT NULL,
  `semester_id` BIGINT NOT NULL,
  `point_type_id` BIGINT NOT NULL,
  `event_id` BIGINT NULL DEFAULT NULL,
  `points` INT NOT NULL,
  `reason` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pt_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `railway`.`users` (`id`),
  CONSTRAINT `fk_pt_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `railway`.`events` (`id`),
  CONSTRAINT `fk_pt_point_type`
    FOREIGN KEY (`point_type_id`)
    REFERENCES `railway`.`point_types` (`id`),
  CONSTRAINT `fk_pt_semester`
    FOREIGN KEY (`semester_id`)
    REFERENCES `railway`.`semesters` (`id`),
  CONSTRAINT `fk_pt_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `railway`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uq_point_tx_student_semester_event` ON `railway`.`point_transactions` (`student_id` ASC, `semester_id` ASC, `event_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pt_student` ON `railway`.`point_transactions` (`student_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pt_semester` ON `railway`.`point_transactions` (`semester_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pt_point_type` ON `railway`.`point_transactions` (`point_type_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pt_event` ON `railway`.`point_transactions` (`event_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pt_created_by` ON `railway`.`point_transactions` (`created_by` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `railway`.`student_semester_summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`student_semester_summary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `railway`.`student_semester_summary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `student_id` BIGINT NOT NULL,
  `semester_id` BIGINT NOT NULL,
  `total_drl` INT NOT NULL DEFAULT '0',
  `total_ctxh` INT NOT NULL DEFAULT '0',
  `total_cdnn` INT NOT NULL DEFAULT '0',
  `rank_label` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sss_semester`
    FOREIGN KEY (`semester_id`)
    REFERENCES `railway`.`semesters` (`id`),
  CONSTRAINT `fk_sss_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `railway`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uq_sss` ON `railway`.`student_semester_summary` (`student_id` ASC, `semester_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_student_semester` ON `railway`.`student_semester_summary` (`student_id` ASC, `semester_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_sss_semester` ON `railway`.`student_semester_summary` (`semester_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
